name: Build
# Tests runs different tests (test_abci_apps, test_abci_cli, test_apps)
# This workflow runs on every push to main or release branch and  every pull requests
# All jobs will pass without running if no *{.go, .mod, .sum} files have been modified
on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goarch: ["amd64"]
        goos: ["linux"]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.go
            "!test/"
            go.mod
            go.sum
            Makefile

      - name: install
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build
        if: "env.GIT_DIFF != ''"
